<?php


namespace SystemUtil;

require_once __DIR__.DIRECTORY_SEPARATOR.'../generated/AutoGeneratedTraits/ConvertGenerated.php';

class Convert extends ComandWrapper {
  
  use \ConvertGenerated;
  use IMagickWrapper;
  /**
   * @var string
   */
  public static $command_path = 'convert';
  
  /**
   * append an image sequence
   * @param $orientation  '-' colspan '+' rowspan
   */
  public function append ( $orientation  = '-') {
    return $this->addOpt( "{$orientation}append" );
  }
  
  /**
   * annotate geometry text annotate the image with text
   * @param $geometry
   * @param $text
   */
  public function annotate($geometry, $text) {
    return $this->addOpt( '-annotate', $geometry,$text );
  }
  
}
