<?php

namespace SystemUtil;

require_once __DIR__.DIRECTORY_SEPARATOR.'../generated/AutoGeneratedTraits/IdentifyGenerated.php';



class Identify extends  ComandWrapper {
  use \IdentifyGenerated;
  use IMagickWrapper;
  /**
   * @var string
   */
  public static $command_path = 'identify';
  
}