<?php

namespace SystemUtil;

require_once __DIR__.DIRECTORY_SEPARATOR.'../generated/AutoGeneratedTraits/MogrifyGenerated.php';

class Mogrify extends  ComandWrapper {
  use \MogrifyGenerated;
  use IMagickWrapper;
  /**
   * @var string
   */
  public static $command_path = 'mogrify';
  
}