<?php

namespace SystemUtil;


require_once __DIR__.DIRECTORY_SEPARATOR.'../generated/AutoGeneratedTraits/MontageGenerated.php';

class Montage extends CommandWrapper {
  use \MontageGenerated;
  use IMagickWrapper;
  /**
   * @var string
   */
  public static $command_path = 'montage';
  
}