<?php

namespace SystemUtil;

use SystemUtil\AutoGeneratedTraits\MontageGenerated;

class Montage extends  ComandWrapper {
  use MontageGenerated;
  use IMagickWrapper;
  /**
   * @var string
   */
  public static $command_path = 'montage';
  
}